// Дані роликів: хук, чому чіпляє, розкадровка.
import { A, C, bg, sparkle, kitchen, dishes, bubbles, notes, person, phone, pin, check, cap, pill, timer, mascot, img, living, thought, endCard, notif, split, svg } from './gen-a.mjs';

export const branches = {
  magic: { tag: 'Чарівний момент', cls: 'b-magic' },
  pain: { tag: 'Біль → продукт → краще життя', cls: 'b-pain' },
  mascot: { tag: 'Маскот і звичка', cls: 'b-mascot' },
};
export const when = {
  now: { t: 'Можна вже зараз', cls: 'w-now' },
  live: { t: 'Зараз · потрібна зйомка', cls: 'w-live' },
  scan: { t: 'Після MVP-13 (справжній скан)', cls: 'w-scan' },
};

export const ads = [
  {
    id: 'A1', branch: 'magic', when: 'scan', name: 'Посуд під музику',
    fmt: 'UGC · 9:16 · 18–22 с', aud: 'жінки 25–44, US/UK, інтереси home, cozy, organizing',
    hook: 'POV: your kitchen just told you where to start',
    why: 'Найчистіша подача «чарівного моменту»: піни з’являються на СПРАВЖНЬОМУ безладі, а далі людина з гарним настроєм просто миє посуд. Той самий шаблон, на якому Chorefriend зробив $26K/міс («фото безладу → мікрокроки з таймінгом»), тільки з атмосферою замість скрінкасту.',
    frames: [
      { t: '0–1.5 с', d: 'Широкий план кухні: гора посуду, крихти. Над речами одна за одною вистрибують коралові піни з номерами.', s: svg(kitchen() + dishes() + pin(124, 160, 1, 'Wash the dishes · 10 min') + pin(40, 176, 4, 'Clear the counter · 5 min', 'down') + pin(150, 290, 3, 'Mop the floor · 5 min') + cap(['POV: your kitchen just', 'told you where to start'])) },
      { t: '1.5–4 с', d: 'Через плече: телефон над мийкою, Moppy сканує — лінія йде згори вниз, піни лягають на ті самі місця.', s: svg(kitchen() + dishes() + phone(46, 60, 88, 190, { img: 'aso-9.6.jpg' }) + pill(90, 290, 'Spotted 4 things to tidy', { tick: true })) },
      { t: '4–6 с', d: 'Екран плану: «Your kitchen, in 4 tiny steps · About 23 min». Тап «Start with step 1».', s: svg(bg('#FFE1E7') + phone(30, 24, 120, 258, { img: 'aso-13.0.jpg' }) + cap(['only 23 minutes?'], 306, { dark: true })) },
      { t: '6–14 с', d: 'Головна частина: телефон на підвіконні (таймер іде вгору), музика, вона миє посуд і пританцьовує. Бульбашки, ноти, теплий ранковий світ.', s: svg(kitchen() + phone(140, 36, 30, 60, { img: 'aso-16.0.jpg' }) + person(78, 92, { arms: 'front' }) + dishes(100, 150) + bubbles(112, 172) + notes(28, 110) + cap(['step 1 · 10 min'], 300, { dark: true })) },
      { t: '14–17 с', d: 'Крупно телефон: «Mark done» — галочка, Moppy підстрибує, конфеті, «1 done · 3 to go».', s: svg(bg('#FFE1E7') + phone(30, 22, 120, 258, { img: 'aso-18.4.jpg' }) + pill(90, 298, '1 done · 3 to go', { tick: true })) },
      { t: '17–20 с', d: 'Повзунок до/після по тій самій кухні + кінцева картка.', s: svg(img('aso-1.0.jpg') + cap(['23 minutes.', "That's it."], 278)) },
    ],
    vo: 'Без голосу — ліцензований трендовий трек; уся історія в тексті на екрані.',
  },
  {
    id: 'A2', branch: 'magic', when: 'scan', name: '«I let an app judge my kitchen»',
    fmt: 'UGC-серія · 9:16 · 20–30 с', aud: 'широка, 22–40; найкраще в TikTok',
    hook: 'I let an app judge my kitchen 😬',
    why: 'Реакція живої людини на результат скану робить «вау» правдоподібним. Серія (кухня → спальня → «та сама шафа») дає привід підписатись, а кожна серія — новий креатив без нового сценарію.',
    frames: [
      { t: '0–2 с', d: 'Селфі-кадр: авторка дивиться в камеру з виразом «ну, давай», за спиною розгардіяш.', s: svg(kitchen() + person(90, 120, { s: 1.6, mood: 'neutral', top: C.top2 }) + cap(['I let an app', 'judge my kitchen 😬'])) },
      { t: '2–6 с', d: 'Запис екрана: камера Moppy, бульбашка «Show me the mess…», тап по затвору.', s: svg(bg('#2C252A') + phone(30, 24, 120, 258, { img: 'aso-6.0.jpg' })) },
      { t: '6–10 с', d: 'Піни вистрибують. Врізка обличчя в кутку: «…only FOUR? and 23 minutes??»', s: svg(img('aso-9.6.jpg') + `<circle cx="140" cy="250" r="30" fill="${C.wall}" stroke="#fff" stroke-width="3"/>` + person(140, 228, { s: 0.85, mood: 'panic', top: C.top2 }) + cap(['only FOUR??'], 304, { dark: true })) },
      { t: '10–22 с', d: 'Таймлапс прибирання з таймером Moppy в кутку (секундомір уперед, не відлік).', s: svg(kitchen({ messy: false }) + person(70, 96, { arms: 'up', top: C.top2 }) + timer(130, 140, '14:52', 22)) },
      { t: '22–26 с', d: 'Повзунок до/після.', s: svg(img('aso-1.0.jpg') + cap(['23:04'], 292, { dark: true })) },
      { t: '26–30 с', d: 'Тизер серії: «Day 2: the bedroom 👀» + «follow for day 2».', s: svg(bg('#E4DDF6') + cap(['Day 2:', 'the bedroom 👀'], 100, { size: 14 }) + mascot('11-looking-magnifier', 40, 160, 100)) },
    ],
    vo: 'Живий голос авторки, субтитри обов’язково.',
  },
  {
    id: 'A3', branch: 'magic', when: 'scan', name: '«Drop your mess» — відповіді на коментарі',
    fmt: 'Відповідь відео на коментар · 15–20 с', aud: 'органіка TikTok/Reels → найкращі в Spark Ads',
    hook: '“do my room next 😭” — ok, let’s see',
    why: 'Цикл залученості: кожен коментар із фото — готовий наступний ролик. Глядач бачить скан на ЧУЖОМУ, тобто будь-якому, безладі — це доводить, що працює не лише на постановочній кухні.',
    frames: [
      { t: '0–2 с', d: 'Наліпка-коментар «do my room next 😭» поверх фото кімнати підписниці.', s: svg(living() + `<g font-family="Nunito,sans-serif"><rect x="14" y="30" width="152" height="34" rx="10" fill="#fff"/><circle cx="30" cy="47" r="9" fill="#F4A6A6"/><text x="44" y="44" font-size="7" font-weight="800" fill="${C.ink}">Reply to @sam.k</text><text x="44" y="56" font-size="8.5" fill="${C.ink}">do my room next 😭</text></g>`) },
      { t: '2–7 с', d: 'Те саме фото в Moppy: лінія скану, піни на речах.', s: svg(living() + pin(130, 162, 1, 'Fold the blanket · 3 min', 'down') + pin(44, 254, 2, 'Pick up the floor · 5 min') + pin(140, 286, 3, 'Clear the toys · 4 min') + pill(90, 28, 'Spotted 3 things to tidy', { tick: true })) },
      { t: '7–13 с', d: 'План із кроками і хвилинами, авторка коментує: «12 minutes, Sam. You got this».', s: svg(bg('#FFE1E7') + phone(30, 24, 120, 258, { img: 'aso-13.0.jpg' }) + cap(['12 minutes, Sam.'], 306, { dark: true })) },
      { t: '13–18 с', d: 'Заклик: «Drop yours 👇» — зі стрілкою в коментарі.', s: svg(bg('#FFF5F7') + cap(['Your turn.', 'Drop your mess 👇'], 100, { size: 14 }) + mascot('08-peek-paws-on-edge', 30, 160, 120)) },
    ],
    vo: 'Голос авторки. ⚠️ Беремо лише фото, які люди надіслали самі й погодились показати.',
  },
  {
    id: 'A4', branch: 'magic', when: 'now', name: 'Повзунок першим — «Same kitchen»',
    fmt: 'Перемонтаж ASO-ролика · 9:16 · 15 с', aud: 'холодна широка; також Apple Search Ads',
    hook: 'Same kitchen. 23 minutes.',
    why: 'Найсильніший кадр, який у нас уже Є — справжня кухня до/після. Ставимо його в першу секунду, а потім «перемотуємо» й показуємо, як це сталося. Нічого знімати не треба: перемонтаж Remotion-проєкту.',
    frames: [
      { t: '0–2 с', d: 'Повзунок їде зліва направо по справжній кухні власника.', s: svg(img('aso-1.0.jpg') + cap(['Same kitchen.', '23 minutes.'])) },
      { t: '2–3 с', d: 'Ефект перемотки — кадри біжать назад до безладу.', s: svg(img('aso-6.0.jpg') + `<rect width="180" height="320" fill="#2C252A" opacity=".25"/><path d="M106 140l-30 20 30 20zM76 140l-30 20 30 20z" fill="#fff"/>`) },
      { t: '3–7 с', d: 'Скан: піни на кухні, «Spotted 4 things to tidy».', s: svg(img('aso-9.6.jpg')) },
      { t: '7–10 с', d: 'План у 4 кроки + Moppy миє посуд разом із тобою.', s: svg(bg('#FFE1E7') + phone(8, 40, 80, 172, { img: 'aso-13.0.jpg' }) + phone(92, 70, 80, 172, { img: 'aso-16.0.jpg' }) + cap(['4 tiny steps'], 282, { dark: true })) },
      { t: '10–15 с', d: 'Кінцева картка: Moppy махає, «Try 7 days free».', s: svg(endCard()) },
    ],
    vo: 'Тиха музика без слів; працює й без звуку.',
  },
  {
    id: 'A5', branch: 'magic', when: 'live', name: 'Спідран «4 steps. Go.»',
    fmt: 'Таймлапс · 9:16 · 15–20 с', aud: 'молодша, 18–34, TikTok',
    hook: '4 steps. Go. ⏱',
    why: 'Спідрани утримують до кінця: глядач хоче побачити фінальний час. Секундомір іде ВПЕРЕД — у Moppy немає «не встиг». Кроки вже є в плані, тож ролик знімається й без справжнього скану.',
    frames: [
      { t: '0–1 с', d: 'Великий секундомір 00:00 поверх безладу, текст «4 steps. Go.»', s: svg(kitchen() + dishes() + timer(90, 140, '00:00', 44) + cap(['4 steps. Go. ⏱'])) },
      { t: '1–12 с', d: 'Чотири швидкі таймлапси (крок — свій кадр), зверху смуга з 4 сегментів заповнюється.', s: svg(kitchen() + person(60, 100, { arms: 'front' }) + bubbles(90, 175) + [0, 1, 2, 3].map(i => `<rect x="${24 + i * 34}" y="18" width="30" height="6" rx="3" fill="${i < 2 ? C.coral : '#EFD5DC'}"/>`).join('') + timer(118, 140, '11:40', 24)) },
      { t: '12–15 с', d: 'Кожне «Mark done» — галочка й конфеті Moppy.', s: svg(bg('#FFE1E7') + phone(30, 24, 120, 258, { img: 'aso-18.4.jpg' }) + check(146, 40, 14)) },
      { t: '15–18 с', d: 'Фінал: «23:04 · All 4 steps done» на чистій кухні.', s: svg(img('aso-3.2.jpg') + timer(90, 150, '23:04', 40) + pill(90, 290, 'All 4 steps done · 23 min', { tick: true })) },
    ],
    vo: 'Ритмічний трек; удари на кожне «Mark done».',
  },
  {
    id: 'B6', branch: 'pain', when: 'live', name: '«Where do I even start»',
    fmt: 'UGC / постановка · 9:16 · 20–25 с', aud: '25–44, «overwhelmed» (НЕ таргет на ADHD — бан Meta)',
    hook: 'For when the mess is so big you can’t start',
    why: 'Найсильніший біль ніші з відгуків: ступор перед безладом. Ролик продає не «прибирання», а полегшення — «просто оце одне, 8 хвилин». Формулюємо через перевантаженість, без діагнозів.',
    frames: [
      { t: '0–3 с', d: 'Людина на дивані дивиться на безлад. Над нею спливають думки: «laundry…», «dishes…», «that pile…», «ugh».', s: svg(living() + person(90, 126, { mood: 'sad' }) + thought(10, 40, 'laundry…') + thought(96, 58, 'dishes…') + thought(30, 86, 'that pile…') + thought(118, 102, 'ugh')) },
      { t: '3–8 с', d: 'Вона відкриває Moppy. Today: «One small thing today. Clear the kitchen counter · About 8 min».', s: svg(bg('#FFF5F7') + phone(30, 24, 120, 258, { img: 'aso-21.5.jpg' }) + cap(['Just this one.'], 306, { dark: true })) },
      { t: '8–15 с', d: 'Вона витирає стільницю, Moppy з ганчіркою в кутку кадру; таймер іде вгору.', s: svg(kitchen() + person(70, 96, { arms: 'front' }) + mascot('16-wiping-counter', 108, 206, 70) + timer(90, 30, '04:12', 24)) },
      { t: '15–20 с', d: 'Вона сидить із чаєм біля чистого куточка й усміхається.', s: svg(living(false) + person(90, 126, { arms: 'front' }) + `<rect x="83" y="188" width="14" height="14" rx="3" fill="#fff" stroke="${C.dim}"/>` + cap(['Done before I could', 'overthink it.'], 278, { dark: true })) },
      { t: '20–24 с', d: 'Кінцева картка.', s: svg(endCard('One small thing a day')) },
    ],
    vo: 'Внутрішній голос шепотом або лише текст; спокійна lo-fi музика.',
  },
  {
    id: 'B7', branch: 'pain', when: 'live', name: '«Guests in 20 minutes»',
    fmt: 'Постановка · 9:16 · 15–20 с', aud: '25–44, сім’ї й пари',
    hook: 'They’re 20 minutes away. 😱',
    why: 'Ситуація, яку впізнає кожен, із чіткою напругою й розв’язкою. Показує, що Moppy допомагає не «колись», а прямо зараз: план за секунди, кроки по 3–5 хвилин.',
    frames: [
      { t: '0–2 с', d: 'Сповіщення поверх безладної вітальні: «we’re 20 min away 🥳». Паніка.', s: svg(living() + person(90, 130, { mood: 'panic', arms: 'up' }) + notif(30, 'Mia', "we're 20 min away 🥳")) },
      { t: '2–6 с', d: 'Moppy: план із кроків із хвилинами, тап «Start».', s: svg(bg('#FFE1E7') + phone(30, 24, 120, 258, { img: 'aso-13.0.jpg' }) + cap(['Moppy, help.'], 306, { dark: true })) },
      { t: '6–14 с', d: 'Швидкі нарізки кроків під ритм, кожен закінчується галочкою.', s: svg(living(false) + person(60, 120, { arms: 'front' }) + check(140, 60, 14) + check(140, 96, 14) + check(140, 132, 14)) },
      { t: '14–18 с', d: 'Дзвінок у двері, вона відчиняє — спокійна, кімната чиста.', s: svg(bg(C.wall2) + `<rect x="0" y="250" width="180" height="70" fill="#E5D6C6"/><rect x="26" y="40" width="80" height="220" rx="4" fill="#C9A27E"/><rect x="20" y="40" width="10" height="220" fill="#B08765"/><circle cx="96" cy="156" r="4" fill="#F5B301"/>` + person(134, 130, {}) + cap(['16 minutes to spare.'], 300, { dark: true })) },
    ],
    vo: 'Текст на екрані + звук дзвінка; секундомір уперед у кутку.',
  },
  {
    id: 'B8', branch: 'pain', when: 'live', name: 'Субота проти 8 хвилин на день',
    fmt: 'Розділений екран · 9:16 · 15 с', aud: 'працюючі 28–45',
    hook: 'Stop losing your weekends to cleaning',
    why: 'Чесне порівняння двох стратегій в одному кадрі: «генеральне в суботу» проти «одна дрібниця щодня». Продає головну ідею Today — одну справу на день, без перевантаження.',
    frames: [
      { t: '0–2 с', d: 'Розділений екран. Зліва «Saturday», справа «8 min a day».', s: svg(split(living() + person(90, 126, { mood: 'sad' }), living(false) + person(90, 126, {})) + cap(['Saturday', 'vs 8 min a day'])) },
      { t: '2–9 с', d: 'Зліва — відра, втома. Справа — ранок, віджет «Wash the dishes · ~10 min», зроблено до кави.', s: svg(split(kitchen() + person(90, 150, { mood: 'sad' }), bg('#FFF5F7') + `<image href="${A}shot06-widgets.jpg" x="30" y="-120" width="120" height="440" preserveAspectRatio="xMidYMax slice"/>`)) },
      { t: '9–13 с', d: 'Зліва секундомір показує 5 годин. Справа людина вже гуляє — вдома спокійно.', s: svg(split(kitchen() + person(90, 160, { mood: 'sad' }) + `<text x="90" y="130" text-anchor="middle" font-family="Lora,serif" font-size="17" fill="${C.ink}" stroke="#fff" stroke-width="3" paint-order="stroke">5:12:40</text>`, living(false) + person(90, 120, { arms: 'up' }) + `<text x="90" y="100" text-anchor="middle" font-family="Lora,serif" font-size="17" fill="${C.ink}" stroke="#fff" stroke-width="3" paint-order="stroke">08:10</text>`)) },
      { t: '13–15 с', d: 'Кінцева картка «One small thing a day».', s: svg(endCard('One small thing a day')) },
    ],
    vo: 'Без голосу.',
  },
  {
    id: 'B9', branch: 'pain', when: 'live', name: '«This app never says you’re behind»',
    fmt: 'Справжня користувачка · 9:16 · 20 с', aud: 'ті, хто кидав chore-трекери (ретаргет, look-alike)',
    hook: 'Every chore app made me feel guilty. This one doesn’t.',
    why: 'Відмінність, якої немає в конкурентів: у Moppy НЕМАЄ прострочень — незроблене переїжджає на завтра, а тиждень рахує кожен маленький день. Знімає реальна людина, що користувалась застосунком, з позначкою партнерства.',
    frames: [
      { t: '0–3 с', d: 'Безіменний «застосунок-докір» (вигаданий, без чужих брендів) із лічильником «Overdue 14».', s: svg(bg('#F3F3F3') + `<g font-family="Nunito,sans-serif"><rect x="30" y="90" width="120" height="150" rx="14" fill="#fff" stroke="#ddd"/><text x="42" y="114" font-size="9" font-weight="800" fill="${C.ink}">Chores</text><rect x="96" y="104" width="44" height="14" rx="7" fill="#8E8E8E"/><text x="118" y="114" font-size="6.6" fill="#fff" text-anchor="middle">Overdue 14</text>${[0, 1, 2, 3].map(i => `<rect x="42" y="${130 + i * 24}" width="96" height="16" rx="5" fill="#F2F2F2"/>`).join('')}</g>` + cap(['Every chore app', 'made me feel guilty.'])) },
      { t: '3–9 с', d: 'Moppy: свайп по кроку — «Move to tomorrow», «Undo». Нічого не червоніє.', s: svg(bg('#FFF5F7') + phone(30, 20, 120, 258, { img: 'aso-16.0.jpg' }) + pill(90, 300, 'Move to tomorrow →', { bgc: '#FFE1E7', fg: '#A8203B' })) },
      { t: '9–14 с', d: 'Тиждень крапками: «3 days this week · Every small day counts».', s: svg(img('shot05-day-week.jpg')) },
      { t: '14–20 с', d: 'Обличчя авторки, спокійно: «It just moves it to tomorrow. That’s it.» + кінцева картка.', s: svg(living(false) + person(90, 100, { s: 1.5, top: C.top2 }) + cap(['It just moves it', 'to tomorrow.'], 278, { dark: true })) },
    ],
    vo: 'Живий голос; підпис «Paid partnership». Жодних вигаданих відгуків.',
  },
  {
    id: 'C10', branch: 'mascot', when: 'now', name: 'Moppy брудніє замість твого дому',
    fmt: 'Повна анімація Remotion · 9:16 · 15 с', aud: 'cozy-ігри, тамагочі, 18–34',
    hook: 'He gets dusty so your home doesn’t',
    why: 'Механіка, якої немає ні в кого: бруд на маскоті — слід ТВОЄЇ зробленої роботи, а миття з бульбашками — винагорода. Затишний формат «тамагочі» чіпляє аудиторію cozy-ігор. Робиться з наявних PNG маскота, без зйомок.',
    frames: [
      { t: '0–2 с', d: 'Чистий пухнастий Moppy: «He gets dusty so your home doesn’t».', s: svg(bg('#FFF5F7') + mascot('05-freshly-washed', 30, 90, 120) + cap(['He gets dusty', "so your home doesn't"])) },
      { t: '2–7 с', d: 'Кожен твій виконаний крок — галочка зверху, а на Moppy осідає трохи пилу.', s: svg(bg('#FFF5F7') + mascot('04-dusty', 30, 90, 120) + check(60, 50, 10) + check(90, 50, 10) + check(120, 50, 10) + `<g fill="#B79C82" opacity=".7"><circle cx="50" cy="150" r="2"/><circle cx="130" cy="130" r="1.6"/><circle cx="140" cy="190" r="2.2"/></g>` + cap(['12 steps done'], 296, { dark: true })) },
      { t: '7–12 с', d: 'Тап по Moppy → миття: піна, бульбашки злітають і лопаються.', s: svg(bg('#D5E9F7') + mascot('05-freshly-washed', 40, 90, 100) + `<image href="${A}foam.svg" x="20" y="180" width="140" height="80"/>` + bubbles(36, 120) + bubbles(146, 140) + bubbles(96, 80)) },
      { t: '12–15 с', d: 'Сяючий чистий Moppy: «Your home’s clean. So is he.» + кінцева картка.', s: svg(bg('#FFF5F7') + mascot('06-room-done', 30, 70, 120) + sparkle(36, 80) + sparkle(150, 100) + sparkle(134, 56, .7) + cap(["Your home's clean.", 'So is he.'], 266, { dark: true })) },
    ],
    vo: 'Мила мелодія + звуки бульбашок.',
  },
  {
    id: 'C11', branch: 'mascot', when: 'now', name: '«One small thing before coffee»',
    fmt: 'Анімація або UGC · 9:16 · 12–15 с', aud: 'ранкові рутини, 22–38',
    hook: 'One small thing before coffee ☕',
    why: 'Показує звичку, а не разову дію: віджет нагадує сам, справа на 10 хвилин закінчується раніше, ніж закипить чайник. Продає Today, віджети й Live Activity, які вже є на ASO-скрінах.',
    frames: [
      { t: '0–2 с', d: 'Ранок, на заблокованому екрані віджет Moppy «Wash the dishes · ~10 min».', s: svg(bg('#2C252A') + `<image href="${A}shot06-widgets.jpg" x="-20" y="-150" width="220" height="470" preserveAspectRatio="xMidYMax slice"/>` + cap(['One small thing', 'before coffee ☕'], 26, { dark: true })) },
      { t: '2–7 с', d: 'Чайник ставиться; поруч — 10 хвилин посуду (в анімованій версії Moppy миє в ілюстрованій кухні).', s: svg(kitchen() + dishes(110, 150) + mascot('15-washing-dishes', 18, 96, 100, true) + bubbles(128, 146)) },
      { t: '7–10 с', d: '«Mark done» — галочка, віджет оновлюється на «1/4».', s: svg(bg('#FFE1E7') + phone(30, 24, 120, 258, { img: 'aso-18.4.jpg' })) },
      { t: '10–13 с', d: 'Кава в чистій кухні, Moppy махає з кутка.', s: svg(kitchen({ messy: false }) + `<rect x="60" y="160" width="20" height="22" rx="4" fill="#fff" stroke="${C.dim}"/><path d="M80 166q8 2 0 10" stroke="${C.dim}" fill="none"/><path d="M66 152q3-6 0-10M74 152q3-6 0-10" stroke="#bbb" fill="none"/>` + mascot('01-good-morning', 100, 184, 76) + cap(['Done before the kettle.'], 300, { dark: true })) },
    ],
    vo: 'ASMR-звуки ранку: чайник, вода, тап.',
  },
];

export const hooks = [
  ['I asked my phone what to clean first', 'магія'],
  ['This is your sign to do just ONE thing', 'біль'],
  ['4 things. 23 minutes. My whole kitchen.', 'магія'],
  ['Cleaning app for people who hate cleaning apps', 'біль'],
  ['Rate my mess: an app counted 4 things', 'магія'],
  ['The pile on your chair has a 6-minute fix', 'біль'],
  ['POV: you stopped cleaning the whole house and did step 1', 'магія'],
  ['My cleaning buddy is a very fluffy dog', 'маскот'],
  ['You don’t need motivation. You need step 1.', 'біль'],
  ['Watch this kitchen go from 😩 to 😌', 'магія'],
  ['No streaks. No guilt. Just one small thing.', 'біль'],
  ['He gets dirty when YOU clean', 'маскот'],
];
